Version 2026.1.0 (#64)
- Feature (#50): Proxy generator following the procedure highlighted by [Pierrick Picaut](https://www.youtube.com/watch?v=0m0tRBUeL5w).
- Enhancement: Eevee Custom Normals is automatically disabled when starting a render. 
- UI: The Execution Time section is now completely disconnected from the Simplify one for clarity
- UI: Selection of Exceptions directly from Viewport (multiple selection available), instead of list selection.
- UI: Texture Size Limit has been un-hidden from the Advanced options, it's now on a dedicated Others section
- UI: Several UI Improvements.
- Fix: `AttributeError: 'NoneType' object has no attribute 'tag_redraw'`.
- Fix: Several small bug fixed.